# Part 1: Theoretical Questions

## 1. What are the different data structures used in Tensorflow?. Give some examples

## 2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example

## 3. Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.

# Part 2: Practical Implementation

## Task 1: Creating and Manipulating Matrices

### 1. Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the values of matrix A.

In [2]:
pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 524.1/524.1 MB 2.9 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 11.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 12.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 69.2 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.8/440.8 kB 39.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.5/126.5 kB 22.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 10.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 64.4 MB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 66.5 MB/s eta 0:00:0000:01:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 68.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.9/22.9 MB 50.2 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.2/94.2 kB 16.0 MB/s e

In [3]:
import tensorflow as tf
A = tf.random.normal((3,3))
print(A)

2023-09-19 06:13:41.904950: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-19 06:13:41.977997: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-19 06:13:41.979578: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-19 06:13:43.235320: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


tf.Tensor(
[[-0.6028863 -1.8400122 -1.0856332]
 [ 1.4129685 -1.4446112  2.0935016]
 [ 1.1400328 -1.5776372 -1.1158601]], shape=(3, 3), dtype=float32)


### 2. Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display the values of matrix B

In [4]:
B = tf.random.truncated_normal((4,4))
print(B)

tf.Tensor(
[[-1.1190333  -0.99588424 -0.971923   -0.09230219]
 [-1.3465135  -0.9314522  -0.40586376  0.8541956 ]
 [-0.8985767  -1.1247842  -0.9296207   0.4713508 ]
 [ 0.24272919 -0.5514233   0.110128    0.6977431 ]], shape=(4, 4), dtype=float32)


### 3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C

In [5]:
C = tf.random.normal((2,2),mean=2,stddev=0.5)
print(C)

tf.Tensor(
[[1.2656236 3.0320735]
 [1.4854817 1.7620182]], shape=(2, 2), dtype=float32)


### 4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.

It is not possible since the matrices are of different shape.

### 5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

## Task 2: Performing Additional Matrix Operations

### 1. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform functions

In [11]:
F = tf.random.uniform((2,2))
print(F)

tf.Tensor(
[[0.17974246 0.5588732 ]
 [0.84498847 0.56375897]], shape=(2, 2), dtype=float32)


### 2. Calculate the transpose of matrix F and store the result in matrix G.

In [13]:
G = tf.transpose(F)
print(G)

tf.Tensor(
[[0.17974246 0.84498847]
 [0.5588732  0.56375897]], shape=(2, 2), dtype=float32)


### 3. Calculate the element-wise exponential of matrix F and store the result in matrix H.

In [15]:
H = tf.exp(F)
print(H)

tf.Tensor(
[[1.1969091 1.7487009]
 [2.327951  1.7572656]], shape=(2, 2), dtype=float32)


### 4. Create a matrix I by concatenating matrix F and matrix G horizontally.

In [19]:
I = tf.concat([F,G],axis=1)
print(I)

tf.Tensor(
[[0.17974246 0.5588732  0.17974246 0.84498847]
 [0.84498847 0.56375897 0.5588732  0.56375897]], shape=(2, 4), dtype=float32)


### 5.Create a matrix J by concatenating matrix F and matrix H vertically. 

In [23]:
J = tf.concat([F,H],axis=0)
print(J)

tf.Tensor(
[[0.17974246 0.5588732 ]
 [0.84498847 0.56375897]
 [1.1969091  1.7487009 ]
 [2.327951   1.7572656 ]], shape=(4, 2), dtype=float32)
